// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const handlerStats = `-- name: HandlerStats :many
WITH runs AS (
    SELECT j.handler,
           avg(extract(epoch FROM (a.finished_at - a.started_at)) * 1000)::double precision AS avg_run_ms
    FROM job_attempts a
    JOIN jobs j ON j.id = a.job_id
    WHERE a.outcome = 'success' AND a.finished_at IS NOT NULL
    GROUP BY j.handler
)
SELECT j.handler,
       count(*)::bigint AS total,
       count(*) FILTER (WHERE j.state = 'pending')::bigint        AS pending,
       count(*) FILTER (WHERE j.state = 'queued')::bigint         AS queued,
       count(*) FILTER (WHERE j.state = 'running')::bigint        AS running,
       count(*) FILTER (WHERE j.state = 'awaiting_retry')::bigint AS awaiting_retry,
       count(*) FILTER (WHERE j.state = 'paused')::bigint         AS paused,
       count(*) FILTER (WHERE j.state = 'success')::bigint        AS success,
       count(*) FILTER (WHERE j.state = 'dead')::bigint           AS dead,
       count(*) FILTER (WHERE j.state = 'cancelled')::bigint      AS cancelled,
       count(*) FILTER (WHERE j.state = 'expired')::bigint        AS expired,
       array_agg(DISTINCT j.queue ORDER BY j.queue)::text[] AS queues,
       max(j.updated_at)::timestamptz AS last_activity_at,
       max(runs.avg_run_ms) AS avg_run_ms
FROM jobs j
LEFT JOIN runs ON runs.handler = j.handler
WHERE ($1::text IS NULL OR j.handler = $1::text)
GROUP BY j.handler
ORDER BY j.handler
`

type HandlerStatsRow struct {
	Handler        string             `json:"handler"`
	Total          int64              `json:"total"`
	Pending        int64              `json:"pending"`
	Queued         int64              `json:"queued"`
	Running        int64              `json:"running"`
	AwaitingRetry  int64              `json:"awaiting_retry"`
	Paused         int64              `json:"paused"`
	Success        int64              `json:"success"`
	Dead           int64              `json:"dead"`
	Cancelled      int64              `json:"cancelled"`
	Expired        int64              `json:"expired"`
	Queues         []string           `json:"queues"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	AvgRunMs       interface{}        `json:"avg_run_ms"`
}

func (q *Queries) HandlerStats(ctx context.Context, handler pgtype.Text) ([]HandlerStatsRow, error) {
	rows, err := q.db.Query(ctx, handlerStats, handler)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandlerStatsRow
	for rows.Next() {
		var i HandlerStatsRow
		if err := rows.Scan(
			&i.Handler,
			&i.Total,
			&i.Pending,
			&i.Queued,
			&i.Running,
			&i.AwaitingRetry,
			&i.Paused,
			&i.Success,
			&i.Dead,
			&i.Cancelled,
			&i.Expired,
			&i.Queues,
			&i.LastActivityAt,
			&i.AvgRunMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueStats = `-- name: QueueStats :many
SELECT queue,
       count(*) FILTER (WHERE state = 'pending')::bigint        AS pending,
       count(*) FILTER (WHERE state = 'queued')::bigint         AS queued,
       count(*) FILTER (WHERE state = 'running')::bigint        AS running,
       count(*) FILTER (WHERE state = 'awaiting_retry')::bigint AS awaiting_retry,
       count(*) FILTER (WHERE state = 'paused')::bigint         AS paused,
       count(*) FILTER (WHERE state = 'success')::bigint        AS success,
       count(*) FILTER (WHERE state = 'dead')::bigint           AS dead,
       count(*) FILTER (WHERE state = 'cancelled')::bigint      AS cancelled,
       count(*) FILTER (WHERE state = 'expired')::bigint        AS expired,
       COALESCE(
           extract(epoch FROM now() - min(created_at) FILTER (WHERE state = 'pending')),
           0
       )::double precision AS oldest_pending_age_seconds
FROM jobs
GROUP BY queue
ORDER BY queue
`

type QueueStatsRow struct {
	Queue                   string  `json:"queue"`
	Pending                 int64   `json:"pending"`
	Queued                  int64   `json:"queued"`
	Running                 int64   `json:"running"`
	AwaitingRetry           int64   `json:"awaiting_retry"`
	Paused                  int64   `json:"paused"`
	Success                 int64   `json:"success"`
	Dead                    int64   `json:"dead"`
	Cancelled               int64   `json:"cancelled"`
	Expired                 int64   `json:"expired"`
	OldestPendingAgeSeconds float64 `json:"oldest_pending_age_seconds"`
}

func (q *Queries) QueueStats(ctx context.Context) ([]QueueStatsRow, error) {
	rows, err := q.db.Query(ctx, queueStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueStatsRow
	for rows.Next() {
		var i QueueStatsRow
		if err := rows.Scan(
			&i.Queue,
			&i.Pending,
			&i.Queued,
			&i.Running,
			&i.AwaitingRetry,
			&i.Paused,
			&i.Success,
			&i.Dead,
			&i.Cancelled,
			&i.Expired,
			&i.OldestPendingAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentJobsByHandler = `-- name: RecentJobsByHandler :many
SELECT id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at FROM jobs
WHERE handler = $1
ORDER BY updated_at DESC
LIMIT $2
`

type RecentJobsByHandlerParams struct {
	Handler   string `json:"handler"`
	PageLimit int32  `json:"page_limit"`
}

func (q *Queries) RecentJobsByHandler(ctx context.Context, arg RecentJobsByHandlerParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, recentJobsByHandler, arg.Handler, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Queue,
			&i.State,
			&i.Payload,
			&i.Handler,
			&i.Priority,
			&i.RetryCount,
			&i.MaxRetries,
			&i.DeliveryCount,
			&i.Version,
			&i.NextCheckAt,
			&i.IdempotencyKey,
			&i.JobType,
			&i.CronExpr,
			&i.StartsAt,
			&i.EndsAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
