// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET state = 'cancelled', next_check_at = NULL, version = version + 1
WHERE id = $1
  AND version = $2
  AND state IN ('pending', 'queued', 'awaiting_retry')
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type CancelJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimJobForExecution = `-- name: ClaimJobForExecution :one
UPDATE jobs
SET state='running',
    delivery_count = delivery_count+1,
    version = version +1 ,
    next_check_at = now() + $1::interval
WHERE id = $2 AND state='queued'
RETURNING id,name,queue,payload,retry_count,max_retries,delivery_count,version
`

type ClaimJobForExecutionParams struct {
	StaleDeltaThreshold pgtype.Interval `json:"stale_delta_threshold"`
	ID                  pgtype.UUID     `json:"id"`
}

type ClaimJobForExecutionRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Queue         string      `json:"queue"`
	Payload       []byte      `json:"payload"`
	RetryCount    int32       `json:"retry_count"`
	MaxRetries    int32       `json:"max_retries"`
	DeliveryCount int32       `json:"delivery_count"`
	Version       int32       `json:"version"`
}

func (q *Queries) ClaimJobForExecution(ctx context.Context, arg ClaimJobForExecutionParams) (ClaimJobForExecutionRow, error) {
	row := q.db.QueryRow(ctx, claimJobForExecution, arg.StaleDeltaThreshold, arg.ID)
	var i ClaimJobForExecutionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.Payload,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs
    (name, queue, payload, priority, max_retries, next_check_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5, now(), $6)
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type CreateJobParams struct {
	Name           string      `json:"name"`
	Queue          string      `json:"queue"`
	Payload        []byte      `json:"payload"`
	Priority       int32       `json:"priority"`
	MaxRetries     int32       `json:"max_retries"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Queue,
		arg.Payload,
		arg.Priority,
		arg.MaxRetries,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobAttempt = `-- name: CreateJobAttempt :one
INSERT INTO job_attempts (job_id, attempt_number, worker_id)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateJobAttemptParams struct {
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	WorkerID      string      `json:"worker_id"`
}

func (q *Queries) CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createJobAttempt, arg.JobID, arg.AttemptNumber, arg.WorkerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteJobById = `-- name: DeleteJobById :one
DELETE FROM jobs WHERE id = $1 RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

func (q *Queries) DeleteJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, deleteJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDueJobs = `-- name: GetDueJobs :many
WITH queued_counts AS (
    SELECT queue, count(*) AS queued_count
    FROM jobs
    WHERE state = 'queued'
    GROUP BY queue
),
ranked AS (
    SELECT j.id, j.name, j.queue, j.state, j.payload, j.priority, j.retry_count, j.max_retries, j.delivery_count, j.version, j.next_check_at, j.idempotency_key, j.created_at, j.updated_at,
        ROW_NUMBER() OVER (
            PARTITION BY j.queue
            ORDER BY (j.priority + $2::float * extract(epoch from j.created_at)) ASC,
                     j.created_at ASC
        ) AS rn
    FROM jobs j
    WHERE j.state IN ('pending', 'awaiting_retry')
      AND j.next_check_at <= now()
)
SELECT ranked.id,ranked.queue,ranked.version FROM ranked
LEFT JOIN queued_counts qc ON qc.queue = ranked.queue
WHERE ranked.rn <= ($1::int - COALESCE(qc.queued_count, 0))
ORDER BY ranked.queue, ranked.rn
`

type GetDueJobsParams struct {
	MaxFetchPerQueue int32   `json:"max_fetch_per_queue"`
	AgingRate        float64 `json:"aging_rate"`
}

type GetDueJobsRow struct {
	ID      pgtype.UUID `json:"id"`
	Queue   string      `json:"queue"`
	Version int32       `json:"version"`
}

func (q *Queries) GetDueJobs(ctx context.Context, arg GetDueJobsParams) ([]GetDueJobsRow, error) {
	rows, err := q.db.Query(ctx, getDueJobs, arg.MaxFetchPerQueue, arg.AgingRate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueJobsRow
	for rows.Next() {
		var i GetDueJobsRow
		if err := rows.Scan(&i.ID, &i.Queue, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobAttemptsByJobId = `-- name: GetJobAttemptsByJobId :many
SELECT id, job_id, attempt_number, worker_id, outcome, result, started_at, finished_at FROM job_attempts
WHERE job_id = $1
ORDER BY attempt_number ASC
LIMIT $2 OFFSET $3
`

type GetJobAttemptsByJobIdParams struct {
	JobID  pgtype.UUID `json:"job_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetJobAttemptsByJobId(ctx context.Context, arg GetJobAttemptsByJobIdParams) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, getJobAttemptsByJobId, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobAttempt
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.WorkerID,
			&i.Outcome,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at FROM jobs WHERE idempotency_key = $1
`

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, idempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at FROM jobs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Fetch LIMIT+1 in the app layer; if len(rows) > limit, has_more=true, trim the extra row.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Queue,
			&i.State,
			&i.Payload,
			&i.Priority,
			&i.RetryCount,
			&i.MaxRetries,
			&i.DeliveryCount,
			&i.Version,
			&i.NextCheckAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueued = `-- name: MarkQueued :many
UPDATE jobs
SET state = 'queued', version = version + 1
WHERE id = ANY($1::uuid[])
  AND state IN ('pending', 'awaiting_retry')
RETURNING id
`

func (q *Queries) MarkQueued(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, markQueued, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimStaleJobs = `-- name: ReclaimStaleJobs :many
UPDATE jobs
SET state = CASE
        WHEN delivery_count >= $1::int THEN 'dead'::job_state
        ELSE 'awaiting_retry'
    END,
    next_check_at = CASE
        WHEN delivery_count >= $1::int THEN NULL
        ELSE now()
    END,
    version = version + 1
WHERE state = 'running' AND next_check_at <= now()
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

func (q *Queries) ReclaimStaleJobs(ctx context.Context, maxDeliveryCount int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, reclaimStaleJobs, maxDeliveryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Queue,
			&i.State,
			&i.Payload,
			&i.Priority,
			&i.RetryCount,
			&i.MaxRetries,
			&i.DeliveryCount,
			&i.Version,
			&i.NextCheckAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobExecutionFailure = `-- name: RecordJobExecutionFailure :execrows
UPDATE jobs
SET retry_count= CASE
        WHEN  retry_count<max_retries THEN retry_count+1
        ELSE retry_count END,
    state=CASE
        WHEN retry_count>=max_retries THEN 'dead'::job_state
        ELSE 'awaiting_retry'::job_state END,
    next_check_at  = CASE
      WHEN retry_count >= max_retries THEN NULL
      ELSE $1::timestamptz END,
    version = version +1
WHERE id = $2 AND version = $3 AND state = 'running'
`

type RecordJobExecutionFailureParams struct {
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
}

func (q *Queries) RecordJobExecutionFailure(ctx context.Context, arg RecordJobExecutionFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordJobExecutionFailure, arg.NextCheckAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshHeartBeat = `-- name: RefreshHeartBeat :execrows
UPDATE jobs
SET next_check_at = now() + $1::interval
WHERE id = $2 and version = $3 and state='running'
`

type RefreshHeartBeatParams struct {
	StaleDeltaThreshold pgtype.Interval `json:"stale_delta_threshold"`
	ID                  pgtype.UUID     `json:"id"`
	Version             int32           `json:"version"`
}

func (q *Queries) RefreshHeartBeat(ctx context.Context, arg RefreshHeartBeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshHeartBeat, arg.StaleDeltaThreshold, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rerunDeadJob = `-- name: RerunDeadJob :one
UPDATE jobs
SET state = 'pending',
    retry_count = 0,
    next_check_at = now(),
    version = version + 1
WHERE id = $1
  AND version = $2
  AND state = 'dead'
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type RerunDeadJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) RerunDeadJob(ctx context.Context, arg RerunDeadJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, rerunDeadJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeOpenAttempt = `-- name: SupersedeOpenAttempt :exec
UPDATE job_attempts
SET outcome = 'superseded', finished_at = now()
WHERE job_id = $1 AND outcome = 'in_progress'
`

func (q *Queries) SupersedeOpenAttempt(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeOpenAttempt, jobID)
	return err
}

const updateJobAttemptExecutionCompletion = `-- name: UpdateJobAttemptExecutionCompletion :execrows
UPDATE job_attempts
SET outcome = $1,
    result = $2,
    finished_at=now()
WHERE id = $3 AND outcome='in_progress'
`

type UpdateJobAttemptExecutionCompletionParams struct {
	Outcome AttemptOutcome `json:"outcome"`
	Result  pgtype.Text    `json:"result"`
	ID      pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateJobAttemptExecutionCompletion(ctx context.Context, arg UpdateJobAttemptExecutionCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobAttemptExecutionCompletion, arg.Outcome, arg.Result, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJobCompletion = `-- name: UpdateJobCompletion :execrows
UPDATE jobs
SET state='success',
    version=version+1,
    next_check_at=NULL
WHERE id = $1 AND version = $2 AND state='running'
`

type UpdateJobCompletionParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobCompletion, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
