// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET state = 'cancelled', next_check_at = NULL, next_run_at = NULL, version = version + 1
WHERE id = $1
  AND version = $2
  AND (state IN ('pending', 'queued', 'awaiting_retry', 'paused')
       OR (state = 'success' AND next_run_at IS NOT NULL))
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

type CancelJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimJobForExecution = `-- name: ClaimJobForExecution :one
WITH claimed AS (
    UPDATE jobs
    SET state='running',
        delivery_count = delivery_count+1,
        version = version +1 ,
        next_check_at = now() + $1::interval
    WHERE jobs.id = $2 AND state='queued'
    RETURNING jobs.id,name,queue,payload,handler,retry_count,max_retries,delivery_count,version,
              job_type,cron_expr,ends_at
),
attempt AS (
    INSERT INTO job_attempts (job_id, worker_id)
    SELECT claimed.id, $3 FROM claimed
    RETURNING job_attempts.id, job_attempts.job_id
)
SELECT c.id, c.name, c.queue, c.payload, c.handler, c.retry_count, c.max_retries,
       c.delivery_count, c.version,
       c.job_type, c.cron_expr, c.ends_at,
       a.id AS attempt_id
FROM claimed c
JOIN attempt a ON a.job_id = c.id
`

type ClaimJobForExecutionParams struct {
	StaleDeltaThreshold pgtype.Interval `json:"stale_delta_threshold"`
	ID                  pgtype.UUID     `json:"id"`
	WorkerID            pgtype.Text     `json:"worker_id"`
}

type ClaimJobForExecutionRow struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Queue         string             `json:"queue"`
	Payload       []byte             `json:"payload"`
	Handler       string             `json:"handler"`
	RetryCount    int32              `json:"retry_count"`
	MaxRetries    int32              `json:"max_retries"`
	DeliveryCount int32              `json:"delivery_count"`
	Version       int32              `json:"version"`
	JobType       JobType            `json:"job_type"`
	CronExpr      pgtype.Text        `json:"cron_expr"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	AttemptID     pgtype.UUID        `json:"attempt_id"`
}

func (q *Queries) ClaimJobForExecution(ctx context.Context, arg ClaimJobForExecutionParams) (ClaimJobForExecutionRow, error) {
	row := q.db.QueryRow(ctx, claimJobForExecution, arg.StaleDeltaThreshold, arg.ID, arg.WorkerID)
	var i ClaimJobForExecutionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.Payload,
		&i.Handler,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.JobType,
		&i.CronExpr,
		&i.EndsAt,
		&i.AttemptID,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs
    (name, queue, payload, handler, priority, max_retries, next_check_at, idempotency_key,
     job_type, cron_expr, next_run_at, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13)
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

type CreateJobParams struct {
	Name           string             `json:"name"`
	Queue          string             `json:"queue"`
	Payload        []byte             `json:"payload"`
	Handler        string             `json:"handler"`
	Priority       int32              `json:"priority"`
	MaxRetries     int32              `json:"max_retries"`
	NextCheckAt    pgtype.Timestamptz `json:"next_check_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	JobType        JobType            `json:"job_type"`
	CronExpr       pgtype.Text        `json:"cron_expr"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Queue,
		arg.Payload,
		arg.Handler,
		arg.Priority,
		arg.MaxRetries,
		arg.NextCheckAt,
		arg.IdempotencyKey,
		arg.JobType,
		arg.CronExpr,
		arg.NextRunAt,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobAttempt = `-- name: CreateJobAttempt :one
INSERT INTO job_attempts (job_id, worker_id)
VALUES ($1, $2)
RETURNING id
`

type CreateJobAttemptParams struct {
	JobID    pgtype.UUID `json:"job_id"`
	WorkerID pgtype.Text `json:"worker_id"`
}

func (q *Queries) CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createJobAttempt, arg.JobID, arg.WorkerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteJobById = `-- name: DeleteJobById :one
DELETE FROM jobs WHERE id = $1 RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

func (q *Queries) DeleteJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, deleteJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeExpiredJobs = `-- name: FinalizeExpiredJobs :many
UPDATE jobs
SET state = 'expired', next_check_at = NULL, next_run_at = NULL, version = version + 1
WHERE ends_at IS NOT NULL
  AND now() >= ends_at
  AND state NOT IN ('running', 'expired')
  AND (next_check_at IS NOT NULL OR next_run_at IS NOT NULL)
RETURNING id
`

func (q *Queries) FinalizeExpiredJobs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, finalizeExpiredJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptLogs = `-- name: GetAttemptLogs :many
SELECT seq, level, line, created_at
FROM job_logs
WHERE attempt_id = $1
  AND created_at >= $2
  AND created_at <  $3
  AND seq > $4
ORDER BY seq ASC
LIMIT $5
`

type GetAttemptLogsParams struct {
	AttemptID pgtype.UUID        `json:"attempt_id"`
	FromTs    pgtype.Timestamptz `json:"from_ts"`
	ToTs      pgtype.Timestamptz `json:"to_ts"`
	AfterSeq  int32              `json:"after_seq"`
	PageLimit int32              `json:"page_limit"`
}

type GetAttemptLogsRow struct {
	Seq       int32              `json:"seq"`
	Level     LogLevel           `json:"level"`
	Line      string             `json:"line"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAttemptLogs(ctx context.Context, arg GetAttemptLogsParams) ([]GetAttemptLogsRow, error) {
	rows, err := q.db.Query(ctx, getAttemptLogs,
		arg.AttemptID,
		arg.FromTs,
		arg.ToTs,
		arg.AfterSeq,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttemptLogsRow
	for rows.Next() {
		var i GetAttemptLogsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Level,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueJobs = `-- name: GetDueJobs :many
WITH queued_counts AS (
    SELECT queue, count(*) AS queued_count
    FROM jobs
    WHERE state = 'queued'
    GROUP BY queue
),
ranked AS (
    SELECT j.id, j.name, j.queue, j.state, j.payload, j.handler, j.priority, j.retry_count, j.max_retries, j.delivery_count, j.version, j.next_check_at, j.idempotency_key, j.job_type, j.cron_expr, j.starts_at, j.ends_at, j.next_run_at, j.created_at, j.updated_at,
        ROW_NUMBER() OVER (
            PARTITION BY j.queue
            ORDER BY (j.priority + $2::float
                      * extract(epoch from COALESCE(j.next_run_at, j.created_at))) ASC,
                     COALESCE(j.next_run_at, j.created_at) ASC
        ) AS rn
    FROM jobs j
    WHERE (
            (j.state IN ('pending', 'awaiting_retry') AND j.next_check_at <= now())
         OR (j.state = 'success' AND j.next_run_at IS NOT NULL AND j.next_run_at <= now())
          )
      AND (j.ends_at IS NULL OR now() < j.ends_at)
)
SELECT ranked.id,ranked.queue,ranked.version FROM ranked
LEFT JOIN queued_counts qc ON qc.queue = ranked.queue
WHERE ranked.rn <= ($1::int - COALESCE(qc.queued_count, 0))
ORDER BY ranked.queue, ranked.rn
`

type GetDueJobsParams struct {
	MaxFetchPerQueue int32   `json:"max_fetch_per_queue"`
	AgingRate        float64 `json:"aging_rate"`
}

type GetDueJobsRow struct {
	ID      pgtype.UUID `json:"id"`
	Queue   string      `json:"queue"`
	Version int32       `json:"version"`
}

func (q *Queries) GetDueJobs(ctx context.Context, arg GetDueJobsParams) ([]GetDueJobsRow, error) {
	rows, err := q.db.Query(ctx, getDueJobs, arg.MaxFetchPerQueue, arg.AgingRate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueJobsRow
	for rows.Next() {
		var i GetDueJobsRow
		if err := rows.Scan(&i.ID, &i.Queue, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobAttempt = `-- name: GetJobAttempt :one
SELECT id, job_id, worker_id, outcome, result, started_at, finished_at FROM job_attempts
WHERE id = $1 AND job_id = $2
`

type GetJobAttemptParams struct {
	ID    pgtype.UUID `json:"id"`
	JobID pgtype.UUID `json:"job_id"`
}

func (q *Queries) GetJobAttempt(ctx context.Context, arg GetJobAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, getJobAttempt, arg.ID, arg.JobID)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkerID,
		&i.Outcome,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobAttemptsByJobId = `-- name: GetJobAttemptsByJobId :many
SELECT id, job_id, worker_id, outcome, result, started_at, finished_at FROM job_attempts
WHERE job_id = $1
ORDER BY started_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type GetJobAttemptsByJobIdParams struct {
	JobID  pgtype.UUID `json:"job_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetJobAttemptsByJobId(ctx context.Context, arg GetJobAttemptsByJobIdParams) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, getJobAttemptsByJobId, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobAttempt
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.WorkerID,
			&i.Outcome,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at FROM jobs WHERE idempotency_key = $1
`

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, idempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobLogs = `-- name: InsertJobLogs :execrows
INSERT INTO job_logs (attempt_id, seq, level, line, created_at)
SELECT
    unnest($1::uuid[]),
    unnest($2::int[]),
    unnest($3::log_level[]),
    unnest($4::text[]),
    unnest($5::timestamptz[])
ON CONFLICT DO NOTHING
`

type InsertJobLogsParams struct {
	AttemptIds []pgtype.UUID        `json:"attempt_ids"`
	Seqs       []int32              `json:"seqs"`
	Levels     []LogLevel           `json:"levels"`
	Lines      []string             `json:"lines"`
	CreatedAts []pgtype.Timestamptz `json:"created_ats"`
}

func (q *Queries) InsertJobLogs(ctx context.Context, arg InsertJobLogsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJobLogs,
		arg.AttemptIds,
		arg.Seqs,
		arg.Levels,
		arg.Lines,
		arg.CreatedAts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at FROM jobs
WHERE (cardinality($1::text[]) = 0 OR state::text = ANY($1::text[]))
  AND ($2::text     IS NULL OR queue = $2::text)
  AND ($3::text   IS NULL OR handler = $3::text)
  AND ($4::job_type IS NULL OR job_type = $4::job_type)
  AND ($5::text    IS NULL
       OR name ILIKE '%' || $5::text || '%'
       OR handler ILIKE '%' || $5::text || '%'
       OR id::text ILIKE '%' || $5::text || '%')
ORDER BY updated_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type ListJobsParams struct {
	States     []string    `json:"states"`
	Queue      pgtype.Text `json:"queue"`
	Handler    pgtype.Text `json:"handler"`
	JobType    NullJobType `json:"job_type"`
	Search     pgtype.Text `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

// Fetch LIMIT+1 in the app layer; if len(rows) > limit, has_more=true, trim the extra row.
// States arrive as text[], not job_state[]: pgx has no encode plan for an enum array unless
// the type is registered on every connection. The API validates each value before it gets here.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.States,
		arg.Queue,
		arg.Handler,
		arg.JobType,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Queue,
			&i.State,
			&i.Payload,
			&i.Handler,
			&i.Priority,
			&i.RetryCount,
			&i.MaxRetries,
			&i.DeliveryCount,
			&i.Version,
			&i.NextCheckAt,
			&i.IdempotencyKey,
			&i.JobType,
			&i.CronExpr,
			&i.StartsAt,
			&i.EndsAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueued = `-- name: MarkQueued :many
UPDATE jobs
SET state = 'queued',
    next_check_at = now() + $1::interval,
    version = version + 1
WHERE id = ANY($2::uuid[])
  AND (state IN ('pending', 'awaiting_retry')
       OR (state = 'success' AND next_run_at IS NOT NULL))
RETURNING id
`

type MarkQueuedParams struct {
	ClaimDeadline pgtype.Interval `json:"claim_deadline"`
	Ids           []pgtype.UUID   `json:"ids"`
}

func (q *Queries) MarkQueued(ctx context.Context, arg MarkQueuedParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, markQueued, arg.ClaimDeadline, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseJob = `-- name: PauseJob :one
UPDATE jobs
SET state = 'paused', next_check_at = NULL, version = version + 1
WHERE id = $1
  AND version = $2
  AND job_type = 'cron'
  AND state IN ('pending', 'queued', 'awaiting_retry', 'success')
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

type PauseJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) PauseJob(ctx context.Context, arg PauseJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, pauseJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimStaleJobs = `-- name: ReclaimStaleJobs :many
UPDATE jobs
SET state = CASE
        WHEN delivery_count >= $1::int THEN 'dead'::job_state
        ELSE 'awaiting_retry'
    END,
    next_check_at = CASE
        WHEN delivery_count >= $1::int THEN NULL
        ELSE now()
    END,
    version = version + 1
WHERE state = 'running' AND next_check_at <= now()
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

func (q *Queries) ReclaimStaleJobs(ctx context.Context, maxDeliveryCount int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, reclaimStaleJobs, maxDeliveryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Queue,
			&i.State,
			&i.Payload,
			&i.Handler,
			&i.Priority,
			&i.RetryCount,
			&i.MaxRetries,
			&i.DeliveryCount,
			&i.Version,
			&i.NextCheckAt,
			&i.IdempotencyKey,
			&i.JobType,
			&i.CronExpr,
			&i.StartsAt,
			&i.EndsAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobExecutionFailure = `-- name: RecordJobExecutionFailure :execrows
UPDATE jobs
SET retry_count= CASE
        WHEN  retry_count<max_retries THEN retry_count+1
        ELSE retry_count END,
    state=CASE
        WHEN retry_count>=max_retries THEN 'dead'::job_state
        ELSE 'awaiting_retry'::job_state END,
    next_check_at  = CASE
      WHEN retry_count >= max_retries THEN NULL
      ELSE $1::timestamptz END,
    next_run_at = CASE
      WHEN retry_count >= max_retries THEN NULL
      ELSE next_run_at END,
    version = version +1
WHERE id = $2 AND version = $3 AND state = 'running'
`

type RecordJobExecutionFailureParams struct {
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
}

func (q *Queries) RecordJobExecutionFailure(ctx context.Context, arg RecordJobExecutionFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordJobExecutionFailure, arg.NextCheckAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshHeartBeats = `-- name: RefreshHeartBeats :many
UPDATE jobs
SET next_check_at = now() + $1::interval
FROM (
    SELECT unnest($2::uuid[]) AS id, unnest($3::int[]) AS version
) AS claim
WHERE jobs.id = claim.id AND jobs.version = claim.version AND jobs.state = 'running'
RETURNING jobs.id
`

type RefreshHeartBeatsParams struct {
	StaleDeltaThreshold pgtype.Interval `json:"stale_delta_threshold"`
	Ids                 []pgtype.UUID   `json:"ids"`
	Versions            []int32         `json:"versions"`
}

func (q *Queries) RefreshHeartBeats(ctx context.Context, arg RefreshHeartBeatsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, refreshHeartBeats, arg.StaleDeltaThreshold, arg.Ids, arg.Versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rerunDeadJob = `-- name: RerunDeadJob :one
UPDATE jobs
SET state = 'pending',
    retry_count = 0,
    delivery_count = 0,
    next_check_at = now(),
    next_run_at = CASE WHEN job_type = 'cron' THEN now() ELSE NULL END,
    version = version + 1
WHERE id = $1
  AND version = $2
  AND state = 'dead'
  AND (ends_at IS NULL OR now() < ends_at)
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

type RerunDeadJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) RerunDeadJob(ctx context.Context, arg RerunDeadJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, rerunDeadJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rescheduleJob = `-- name: RescheduleJob :one
UPDATE jobs
SET job_type       = $1,
    cron_expr      = $2,
    starts_at      = $3,
    ends_at        = $4,
    next_run_at    = $5,
    state          = CASE WHEN state = 'paused' THEN 'paused'::job_state
                          ELSE 'pending'::job_state END,
    next_check_at  = CASE WHEN state = 'paused' THEN NULL
                          ELSE $6::timestamptz END,
    retry_count    = 0,
    delivery_count = 0,
    version        = version + 1
WHERE id = $7
  AND version = $8
  AND state IN ('pending', 'awaiting_retry', 'success', 'expired', 'paused')
  AND (state <> 'paused' OR $1::job_type = 'cron')
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

type RescheduleJobParams struct {
	JobType     JobType            `json:"job_type"`
	CronExpr    pgtype.Text        `json:"cron_expr"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	NextRunAt   pgtype.Timestamptz `json:"next_run_at"`
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
}

func (q *Queries) RescheduleJob(ctx context.Context, arg RescheduleJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, rescheduleJob,
		arg.JobType,
		arg.CronExpr,
		arg.StartsAt,
		arg.EndsAt,
		arg.NextRunAt,
		arg.NextCheckAt,
		arg.ID,
		arg.Version,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeJob = `-- name: ResumeJob :one
UPDATE jobs
SET state = 'pending',
    next_check_at  = next_run_at,
    retry_count    = 0,
    delivery_count = 0,
    version        = version + 1
WHERE id = $1 AND version = $2 AND state = 'paused'
RETURNING id, name, queue, state, payload, handler, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, job_type, cron_expr, starts_at, ends_at, next_run_at, created_at, updated_at
`

type ResumeJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) ResumeJob(ctx context.Context, arg ResumeJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, resumeJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Handler,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.JobType,
		&i.CronExpr,
		&i.StartsAt,
		&i.EndsAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeOpenAttempts = `-- name: SupersedeOpenAttempts :exec
UPDATE job_attempts
SET outcome = 'superseded', finished_at = now()
WHERE job_id = ANY($1::uuid[]) AND outcome = 'in_progress'
`

func (q *Queries) SupersedeOpenAttempts(ctx context.Context, jobIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeOpenAttempts, jobIds)
	return err
}

const updateJobAttemptExecutionCompletion = `-- name: UpdateJobAttemptExecutionCompletion :execrows
UPDATE job_attempts
SET outcome = $1,
    result = $2,
    finished_at=now()
WHERE id = $3 AND outcome='in_progress'
`

type UpdateJobAttemptExecutionCompletionParams struct {
	Outcome AttemptOutcome `json:"outcome"`
	Result  pgtype.Text    `json:"result"`
	ID      pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateJobAttemptExecutionCompletion(ctx context.Context, arg UpdateJobAttemptExecutionCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobAttemptExecutionCompletion, arg.Outcome, arg.Result, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJobCompletion = `-- name: UpdateJobCompletion :execrows
UPDATE jobs
SET state = CASE WHEN job_type = 'cron' AND $1::timestamptz IS NULL
                 THEN 'expired'::job_state
                 ELSE 'success'::job_state END,
    next_check_at  = NULL,
    next_run_at    = $1,
    retry_count    = 0,
    delivery_count = 0,
    version        = version + 1
WHERE id = $2 AND version = $3 AND state = 'running'
`

type UpdateJobCompletionParams struct {
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	ID        pgtype.UUID        `json:"id"`
	Version   int32              `json:"version"`
}

func (q *Queries) UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobCompletion, arg.NextRunAt, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLostJob = `-- name: UpdateLostJob :many
WITH lost AS (
    UPDATE jobs
    SET state = 'pending',
        delivery_count = jobs.delivery_count + 1,
        next_check_at = now(),
        version = jobs.version + 1
    WHERE jobs.state = 'queued'
      AND jobs.next_check_at <= now()
    RETURNING jobs.id
),
attempt AS (
    INSERT INTO job_attempts (job_id, worker_id, outcome, result, finished_at)
    SELECT lost.id, NULL, 'lost', $1::text, now() FROM lost
    RETURNING job_attempts.job_id
)
SELECT lost.id FROM lost JOIN attempt ON attempt.job_id = lost.id
`

// A queued job past its claim deadline was never picked up by any worker, so it goes back to pending.
func (q *Queries) UpdateLostJob(ctx context.Context, result string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, updateLostJob, result)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
