// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET state = 'cancelled', next_check_at = NULL, version = version + 1
WHERE id = $1
  AND version = $2
  AND state IN ('pending', 'queued', 'awaiting_retry')
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type CancelJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs
    (name, queue, payload, priority, max_retries, next_check_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5, now(), $6)
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type CreateJobParams struct {
	Name           string      `json:"name"`
	Queue          string      `json:"queue"`
	Payload        []byte      `json:"payload"`
	Priority       int32       `json:"priority"`
	MaxRetries     int32       `json:"max_retries"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Queue,
		arg.Payload,
		arg.Priority,
		arg.MaxRetries,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobAttempt = `-- name: CreateJobAttempt :one
INSERT INTO job_attempts
    (job_id, attempt_number, worker_id)
VALUES ($1, $2, $3)
RETURNING id, job_id, attempt_number, worker_id, outcome, error, started_at, finished_at
`

type CreateJobAttemptParams struct {
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	WorkerID      string      `json:"worker_id"`
}

func (q *Queries) CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, createJobAttempt, arg.JobID, arg.AttemptNumber, arg.WorkerID)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.Outcome,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteJobById = `-- name: DeleteJobById :one
DELETE FROM jobs WHERE id = $1 RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

func (q *Queries) DeleteJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, deleteJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobAttemptsByJobId = `-- name: GetJobAttemptsByJobId :many
SELECT id, job_id, attempt_number, worker_id, outcome, error, started_at, finished_at FROM job_attempts
WHERE job_id = $1
ORDER BY attempt_number ASC
LIMIT $2 OFFSET $3
`

type GetJobAttemptsByJobIdParams struct {
	JobID  pgtype.UUID `json:"job_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetJobAttemptsByJobId(ctx context.Context, arg GetJobAttemptsByJobIdParams) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, getJobAttemptsByJobId, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobAttempt
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.WorkerID,
			&i.Outcome,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at FROM jobs WHERE idempotency_key = $1
`

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, idempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at FROM jobs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Fetch LIMIT+1 in the app layer; if len(rows) > limit, has_more=true, trim the extra row.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Queue,
			&i.State,
			&i.Payload,
			&i.Priority,
			&i.RetryCount,
			&i.MaxRetries,
			&i.DeliveryCount,
			&i.Version,
			&i.NextCheckAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHandlerFailure = `-- name: RecordHandlerFailure :one
UPDATE jobs
SET retry_count = retry_count + 1,
    state = CASE WHEN retry_count + 1 >= max_retries THEN 'dead' ELSE 'awaiting_retry' END,
    next_check_at = CASE WHEN retry_count + 1 >= max_retries THEN NULL ELSE $3 END,
    version = version + 1
WHERE id = $1 AND version = $2
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type RecordHandlerFailureParams struct {
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
}

func (q *Queries) RecordHandlerFailure(ctx context.Context, arg RecordHandlerFailureParams) (Job, error) {
	row := q.db.QueryRow(ctx, recordHandlerFailure, arg.ID, arg.Version, arg.NextCheckAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshHeartbeat = `-- name: RefreshHeartbeat :one
UPDATE jobs
SET next_check_at = now() + $3::interval,
    version = version + 1
WHERE id = $1 AND version = $2 AND state = 'running'
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type RefreshHeartbeatParams struct {
	ID             pgtype.UUID     `json:"id"`
	Version        int32           `json:"version"`
	StaleThreshold pgtype.Interval `json:"stale_threshold"`
}

func (q *Queries) RefreshHeartbeat(ctx context.Context, arg RefreshHeartbeatParams) (Job, error) {
	row := q.db.QueryRow(ctx, refreshHeartbeat, arg.ID, arg.Version, arg.StaleThreshold)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rerunDeadJob = `-- name: RerunDeadJob :one
UPDATE jobs
SET state = 'pending',
    retry_count = 0,
    next_check_at = now(),
    version = version + 1
WHERE id = $1
  AND version = $2
  AND state = 'dead'
RETURNING id, name, queue, state, payload, priority, retry_count, max_retries, delivery_count, version, next_check_at, idempotency_key, created_at, updated_at
`

type RerunDeadJobParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) RerunDeadJob(ctx context.Context, arg RerunDeadJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, rerunDeadJob, arg.ID, arg.Version)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Queue,
		&i.State,
		&i.Payload,
		&i.Priority,
		&i.RetryCount,
		&i.MaxRetries,
		&i.DeliveryCount,
		&i.Version,
		&i.NextCheckAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobAttemptOutcome = `-- name: UpdateJobAttemptOutcome :one
UPDATE job_attempts
SET outcome = $2, error = $3, finished_at = now()
WHERE id = $1
RETURNING id, job_id, attempt_number, worker_id, outcome, error, started_at, finished_at
`

type UpdateJobAttemptOutcomeParams struct {
	ID      pgtype.UUID    `json:"id"`
	Outcome AttemptOutcome `json:"outcome"`
	Error   pgtype.Text    `json:"error"`
}

func (q *Queries) UpdateJobAttemptOutcome(ctx context.Context, arg UpdateJobAttemptOutcomeParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, updateJobAttemptOutcome, arg.ID, arg.Outcome, arg.Error)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.Outcome,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
