// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptOutcome string

const (
	AttemptOutcomeInProgress AttemptOutcome = "in_progress"
	AttemptOutcomeSuccess    AttemptOutcome = "success"
	AttemptOutcomeFailed     AttemptOutcome = "failed"
	AttemptOutcomeCancelled  AttemptOutcome = "cancelled"
	AttemptOutcomeSuperseded AttemptOutcome = "superseded"
)

func (e *AttemptOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptOutcome(s)
	case string:
		*e = AttemptOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptOutcome: %T", src)
	}
	return nil
}

type NullAttemptOutcome struct {
	AttemptOutcome AttemptOutcome `json:"attempt_outcome"`
	Valid          bool           `json:"valid"` // Valid is true if AttemptOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptOutcome), nil
}

func (e AttemptOutcome) Valid() bool {
	switch e {
	case AttemptOutcomeInProgress,
		AttemptOutcomeSuccess,
		AttemptOutcomeFailed,
		AttemptOutcomeCancelled,
		AttemptOutcomeSuperseded:
		return true
	}
	return false
}

func AllAttemptOutcomeValues() []AttemptOutcome {
	return []AttemptOutcome{
		AttemptOutcomeInProgress,
		AttemptOutcomeSuccess,
		AttemptOutcomeFailed,
		AttemptOutcomeCancelled,
		AttemptOutcomeSuperseded,
	}
}

type JobState string

const (
	JobStatePending       JobState = "pending"
	JobStateQueued        JobState = "queued"
	JobStateRunning       JobState = "running"
	JobStateAwaitingRetry JobState = "awaiting_retry"
	JobStateSuccess       JobState = "success"
	JobStateDead          JobState = "dead"
	JobStateCancelled     JobState = "cancelled"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState `json:"job_state"`
	Valid    bool     `json:"valid"` // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

func (e JobState) Valid() bool {
	switch e {
	case JobStatePending,
		JobStateQueued,
		JobStateRunning,
		JobStateAwaitingRetry,
		JobStateSuccess,
		JobStateDead,
		JobStateCancelled:
		return true
	}
	return false
}

func AllJobStateValues() []JobState {
	return []JobState{
		JobStatePending,
		JobStateQueued,
		JobStateRunning,
		JobStateAwaitingRetry,
		JobStateSuccess,
		JobStateDead,
		JobStateCancelled,
	}
}

type Job struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Queue          string             `json:"queue"`
	State          JobState           `json:"state"`
	Payload        []byte             `json:"payload"`
	Priority       int32              `json:"priority"`
	RetryCount     int32              `json:"retry_count"`
	MaxRetries     int32              `json:"max_retries"`
	DeliveryCount  int32              `json:"delivery_count"`
	Version        int32              `json:"version"`
	NextCheckAt    pgtype.Timestamptz `json:"next_check_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type JobAttempt struct {
	ID            pgtype.UUID        `json:"id"`
	JobID         pgtype.UUID        `json:"job_id"`
	AttemptNumber int32              `json:"attempt_number"`
	WorkerID      string             `json:"worker_id"`
	Outcome       AttemptOutcome     `json:"outcome"`
	Result        pgtype.Text        `json:"result"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}
