// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelJob(ctx context.Context, arg CancelJobParams) (Job, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (JobAttempt, error)
	DeleteJobById(ctx context.Context, id pgtype.UUID) (Job, error)
	GetAllJobs(ctx context.Context, arg GetAllJobsParams) ([]Job, error)
	GetJobAttemptsByJobId(ctx context.Context, arg GetJobAttemptsByJobIdParams) ([]JobAttempt, error)
	GetJobById(ctx context.Context, id pgtype.UUID) (Job, error)
	GetJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Job, error)
	RetryJob(ctx context.Context, id pgtype.UUID) (Job, error)
	UpdateJobAttemptHeartbeat(ctx context.Context, id pgtype.UUID) (JobAttempt, error)
	UpdateJobAttemptOutcome(ctx context.Context, arg UpdateJobAttemptOutcomeParams) (JobAttempt, error)
	UpdateJobEffectivePriority(ctx context.Context, arg UpdateJobEffectivePriorityParams) (Job, error)
	UpdateJobPriority(ctx context.Context, arg UpdateJobPriorityParams) (Job, error)
	UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error)
	UpdateRetryCount(ctx context.Context, id pgtype.UUID) (Job, error)
}

var _ Querier = (*Queries)(nil)
